### ISSUE TITLE
Missing IMWRITE_JPEG_SAMPLING_FACTOR constants

### ISSUE THREAD

**Issue by zaquest** [UrielCh/opencv4nodejs#115]
The list of missing constants:

  * IMWRITE_JPEG_SAMPLING_FACTOR
  * IMWRITE_JPEG_SAMPLING_FACTOR_411
  * IMWRITE_JPEG_SAMPLING_FACTOR_420
  * IMWRITE_JPEG_SAMPLING_FACTOR_422
  * IMWRITE_JPEG_SAMPLING_FACTOR_440
  * IMWRITE_JPEG_SAMPLING_FACTOR_444
  
This makes it impossible to change sampling factor from the default 4:2:0 to turn off chroma down-sampling for example.

**Comment by UrielCh** [comment]
For now, you can define them in your code and use them directly. Constant values are just numbers.

Alternatively, open a PR if you want to share those constants with the community.
