### ISSUE TITLE
Wrong function definitions for some calc3d functions [Fix included]

### ISSUE THREAD

**Issue by johnwo90** [UrielCh/opencv4nodejs#117]
Using @u4/opencv4nodejs version: 6.5.2

Been working on some distortion-correction stuff and had problems using some functions, specifically `cv.calibrateCamera` and `cv.projectPoints`.

They're defined as follows:
```
export function calibrateCamera(objectPoints: Point3[], imagePoints: Point2[], imageSize: Size, cameraMatrix: Mat, distCoeffs: number[], flags?: number, criteria?: TermCriteria): CalibrateCameraRet;

export function projectPoints(objectPoints: Point3[], imagePoints: Point2[], rvec: Vec3, tvec: Vec3, cameraMatrix: Mat, distCoeffs: number[], aspectRatio?: number): { imagePoints: Point2[], jacobian: Mat };
```

**calibrateCamera**:
The binding expects `std::vector<std::vector<cv::Point3f>>, std::vector<std::vector<cv::Point2f>>, ...` but calib3d.d.ts defines the two first arguments as `objectPoints : Point3[], imagePoints : Point2[]`.

Fix: Either change calib3d.d.ts or circumvent the typechecker: 
```
cv.calibrateCamera(objectPoints as unknown as cv.Point3[], imagePoints as unknown as  cv.Point2[], imageSize, cameraMatrix, distCoeffs);
```

**projectPoints**:
Similar problem. The binding expects `std::vector<cv::Point3d>, cv::Vec3d, cv::Vec3d, cv::Mat, std::vector<double>, double`.
cv.d.ts defines it as such `export function projectPoints(objectPoints: Point3[], imagePoints: Point2[], rvec: Vec3, tvec: Vec3, cameraMatrix: Mat, distCoeffs: number[], aspectRatio?: number): { imagePoints: Point2[], jacobian: Mat };`.
`imagePoints` is not needed.

Fix: Simply remove the `imagePoints` argument from the definition.

I'm pretty sure there are other, similar issues present in not-so-oftenly-used functions.

**Comment by UrielCh** [comment]
there is the implementation:
```c++
struct CalibrateCameraWorker : public CatchCvExceptionWorker {
public:
  std::vector<std::vector<cv::Point3f>> objectPoints;
  std::vector<std::vector<cv::Point2f>> imagePoints;
  cv::Size2d imageSize;
  cv::Mat cameraMatrix;
  std::vector<double> distCoeffs;
  int flags = 0;
  cv::TermCriteria criteria = cv::TermCriteria(cv::TermCriteria::COUNT + cv::TermCriteria::EPS, 30, DBL_EPSILON);

  double returnValue;
  std::vector<cv::Vec3d> rvecs;
  std::vector<cv::Vec3d> tvecs;

  cv::Mat _rvecs;
  cv::Mat _tvecs;

  virtual ~CalibrateCameraWorker() {
  }

  std::string executeCatchCvExceptionWorker() {
    returnValue = cv::calibrateCamera(objectPoints, imagePoints, imageSize, cameraMatrix, distCoeffs, rvecs, tvecs, flags, criteria);
    return "";
  }

  v8::Local<v8::Value> getReturnValue() {
    v8::Local<v8::Object> ret = Nan::New<v8::Object>();
    Nan::Set(ret, Nan::New("returnValue").ToLocalChecked(), FF::DoubleConverter::wrap(returnValue));
    Nan::Set(ret, Nan::New("rvecs").ToLocalChecked(), Vec3::ArrayConverter::wrap(rvecs));
    Nan::Set(ret, Nan::New("tvecs").ToLocalChecked(), Vec3::ArrayConverter::wrap(tvecs));
    Nan::Set(ret, Nan::New("distCoeffs").ToLocalChecked(), FF::DoubleArrayConverter::wrap(distCoeffs));
    return ret;
  }

  bool unwrapRequiredArgs(Nan::NAN_METHOD_ARGS_TYPE info) {
    return (
        Point3::ArrayOfArraysWithCastConverter<cv::Point3f>::arg(0, &objectPoints, info) || Point2::ArrayOfArraysWithCastConverter<cv::Point2f>::arg(1, &imagePoints, info) || Size::Converter::arg(2, &imageSize, info) || Mat::Converter::arg(3, &cameraMatrix, info) || FF::DoubleArrayConverter::arg(4, &distCoeffs, info));
  }

  bool unwrapOptionalArgs(Nan::NAN_METHOD_ARGS_TYPE info) {
    return (
        FF::IntConverter::optArg(5, &flags, info) || TermCriteria::Converter::optArg(6, &criteria, info));
  }

  bool hasOptArgsObject(Nan::NAN_METHOD_ARGS_TYPE info) {
    return FF::isArgObject(info, 5);
  }

  bool unwrapOptionalArgsFromOpts(Nan::NAN_METHOD_ARGS_TYPE info) {
    v8::Local<v8::Object> opts = info[5]->ToObject(Nan::GetCurrentContext()).ToLocalChecked();
    return (
        FF::IntConverter::optProp(&flags, "flags", opts) || TermCriteria::Converter::optProp(&criteria, "criteria", opts));
  }
};
```

and you want to update:
```ts
export function calibrateCamera(objectPoints: Point3[], imagePoints: Point2[], imageSize: Size, cameraMatrix: Mat, distCoeffs: number[], flags?: number, criteria?: TermCriteria): CalibrateCameraRet;
// to
export function calibrateCamera(objectPoints: ?????, imagePoints: ???????, imageSize, cameraMatrix, distCoeffs);
```

**Comment by UrielCh** [comment]
`returnValue = cv::calibrateCamera(objectPoints, imagePoints, imageSize, cameraMatrix, distCoeffs, rvecs, tvecs, flags, criteria);`

is linked to 

`double 	cv::calibrateCamera (InputArrayOfArrays objectPoints, InputArrayOfArrays imagePoints, Size imageSize, InputOutputArray cameraMatrix, InputOutputArray distCoeffs, OutputArrayOfArrays rvecs, OutputArrayOfArrays tvecs, int flags=0, TermCriteria criteria=TermCriteria(TermCriteria::COUNT+TermCriteria::EPS, 30, DBL_EPSILON))`


objectPoints => InputArrayOfArrays objectPoints
imagePoints => InputArrayOfArrays imagePoints
imageSize  => Size imageSize
cameraMatrix =>  InputOutputArray cameraMatrix
distCoeffs => InputOutputArray distCoeffs
rvecs => OutputArrayOfArrays rvecs
tvecs => OutputArrayOfArrays tvecs
flags => int flags=0
criteria => TermCriteria criteria=TermCriteria(TermCriteria::COUNT+TermCriteria::EPS, 30, DBL_EPSILON))

**Comment by UrielCh** [comment]
for `projectPoints`, I see the error 👍
