### ISSUE TITLE
'build-opencv' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by abranasays** [UrielCh/opencv4nodejs#119]
I have never worked with opencv before. I'm trying to install opencv with below command on Windows 10. 

```
choco install opencv --package-parameters '/Environment'
```
The opencv install without error from chocolate. But When I run below command in my project It is giving me Errors:
```
npm link
build-opencv --nobuild rebuild      <-- giving error
```
Error:
```
'build-opencv' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by hwang1607** [comment]
How did you fix this
