### ISSUE TITLE
Node20, Electron28 support

### ISSUE THREAD

**Issue by sollosollo4** [UrielCh/opencv4nodejs#121]
The libraries for working with Electron and NodeJs of the listed versions are not compiled.
Node.js v20.10.0
electron: 28.0.0
opencv: 4.9.0
node-gyp: 10.0.1
Python 3.12.1
MSVC: 
Build command: npx build-opencv --electron --version 4.9.0 build
I also tried for versions (all this time I was updating the local opencv):
❌4.8.0
❌4.7.0
❌4.6.0
❌4.5.5
I don't think that downgrading NodeJS is a good practice for working with opencv, since other dependencies in the project may also stop working. Should I wait for support, or detailed instructions on how to make this work?
[full_debug_log.txt](https://github.com/UrielCh/opencv4nodejs/files/13881010/full_debug_log.txt)

**Comment by sollosollo4** [comment]
Here are my steps to fix this problem:

1. install cv 4.8.0 and set package.json this:
```
"opencv4nodejs": {
    "autoBuildOpencvVersion": "4.8.0"
  },
```
2. install this https://github.com/UrielCh/npm-opencv-build
3. run this `npx opencv-build-npm --version=4.8.0 --nocontrib` - wait very long (u need install cmake and set PATH for cmake before running this)
4. run this `npx build-opencv --electron --version 4.8.0 build`
5. And get it. I can use `const cv = require('@u4/opencv4nodejs');`

**Comment by UrielCh** [comment]
I had update the lib to support up to `4.9.0`
