### ISSUE TITLE
error on installing 

### ISSUE THREAD

**Issue by evinxnl** [UrielCh/opencv4nodejs#127]
ERR! build Compilation failed, previous calls:
ERR! build rimraf C:\Users\kpons\source\repos\jscheidelaar\pneumacision\node_modules\@u4\opencv-build\dist\opencv-4.5.5-d8111\build C:\Users\kpons\source\repos\jscheidelaar\pneumacision\node_modules\@u4\opencv-build\dist\opencv-4.5.5-d8111\opencv C:\Users\kpons\source\repos\jscheidelaar\pneumacision\node_modules\@u4\opencv-build\dist\opencv-4.5.5-d8111\opencv_contrib
ERR! build mkdir -p C:\Users\kpons\source\repos\jscheidelaar\pneumacision\node_modules\@u4\opencv-build\dist\opencv-4.5.5-d8111\build
ERR! build cd C:\Users\kpons\source\repos\jscheidelaar\pneumacision\node_modules\@u4\opencv-build\dist\opencv-4.5.5-d8111
ERR! build git clone --quiet -b 4.5.5 --single-branch --depth 1 --progress https://github.com/opencv/opencv_contrib.git C:\Users\kpons\source\repos\jscheidelaar\pneumacision\node_modules\@u4\opencv-build\dist\opencv-4.5.5-d8111\opencv_contrib
ERR! build git clone --quiet -b 4.5.5 --single-branch --depth 1 --progress https://github.com/opencv/opencv.git C:\Users\kpons\source\repos\jscheidelaar\pneumacision\node_modules\@u4\opencv-build\dist\opencv-4.5.5-d8111\opencv
ERR! build export OPENCV_BIN_DIR=C:\Users\kpons\source\repos\jscheidelaar\pneumacision\node_modules\@u4\opencv-build\dist\opencv-4.5.5-d8111\build\bin\Release
ERR! build export OPENCV_INCLUDE_DIR=
ERR! build export OPENCV_LIB_DIR=C:\Users\kpons\source\repos\jscheidelaar\pneumacision\node_modules\@u4\opencv-build\dist\opencv-4.5.5-d8111\build\lib\Release
ERR! build cd C:\Users\kpons\source\repos\jscheidelaar\pneumacision\node_modules\@u4\opencv-build\dist\opencv-4.5.5-d8111\build
ERR! build cmake C:\Users\kpons\source\repos\jscheidelaar\pneumacision\node_modules\@u4\opencv-build\dist\opencv-4.5.5-d8111\opencv -G "Visual Studio 17 2022" -DCMAKE_INSTALL_PREFIX=C:\Users\kpons\source\repos\jscheidelaar\pneumacision\node_modules\@u4\opencv-build\dist\opencv-4.5.5-d8111\build -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_TYPES=Release -DBUILD_EXAMPLES=OFF -DBUILD_DOCS=OFF -DBUILD_TESTS=OFF -DBUILD_opencv_dnn=ON -DENABLE_FAST_MATH=ON -DBUILD_PERF_TESTS=OFF -DBUILD_JAVA=OFF -DBUILD_ZLIB=OFF -DCUDA_NVCC_FLAGS=--expt-relaxed-constexpr -DWITH_VTK=OFF -DOPENCV_ENABLE_NONFREE=ON -DOPENCV_EXTRA_MODULES_PATH=C:\Users\kpons\source\repos\jscheidelaar\pneumacision\node_modules\@u4\opencv-build\dist\opencv-4.5.5-d8111\opencv_contrib\modules -DBUILD_opencv_apps=OFF -DBUILD_opencv_aruco=OFF -DBUILD_opencv_bgsegm=OFF -DBUILD_opencv_bindings_generator=OFF -DBUILD_opencv_bioinspired=OFF -DBUILD_opencv_calib3d=ON -DBUILD_opencv_ccalib=OFF -DBUILD_opencv_core=ON -DBUILD_opencv_datasets=OFF -DBUILD_opencv_dnn=ON -DBUILD_opencv_dnn_objdetect=OFF -DBUILD_opencv_dpm=OFF -DBUILD_opencv_face=ON -DBUILD_opencv_features2d=ON -DBUILD_opencv_flann=ON -DBUILD_opencv_fuzzy=OFF -DBUILD_opencv_gapi=ON -DBUILD_opencv_hfs=OFF -DBUILD_opencv_highgui=ON -DBUILD_opencv_img_hash=ON -DBUILD_opencv_imgcodecs=ON -DBUILD_opencv_imgproc=ON -DBUILD_opencv_java_bindings_generator=OFF -DBUILD_opencv_js=OFF -DBUILD_opencv_line_descriptor=OFF -DBUILD_opencv_ml=ON -DBUILD_opencv_objc_bindings_generator=OFF -DBUILD_opencv_objdetect=ON -DBUILD_opencv_optflow=OFF -DBUILD_opencv_phase_unwrapping=OFF -DBUILD_opencv_photo=ON -DBUILD_opencv_python3=OFF -DBUILD_opencv_python_bindings_generator=OFF -DBUILD_opencv_python_tests=ON -DBUILD_opencv_reg=OFF -DBUILD_opencv_rgbd=OFF -DBUILD_opencv_saliency=OFF -DBUILD_opencv_shape=OFF -DBUILD_opencv_stereo=OFF -DBUILD_opencv_stitching=OFF -DBUILD_opencv_structured_light=OFF -DBUILD_opencv_superres=OFF -DBUILD_opencv_surface_matching=OFF -DBUILD_opencv_text=ON -DBUILD_opencv_tracking=ON -DBUILD_opencv_ts=OFF -DBUILD_opencv_video=ON -DBUILD_opencv_videoio=ON -DBUILD_opencv_videostab=ON -DBUILD_opencv_wechat_qrcode=OFF -DBUILD_opencv_world=OFF -DBUILD_opencv_xfeatures2d=ON -DBUILD_opencv_ximgproc=ON -DBUILD_opencv_xobjdetect=OFF -DBUILD_opencv_xphoto=OFF -DWITH_CUDA=ON -DWITH_CUDNN=ON -DOPENCV_DNN_CUDA=ON -DCUDA_FAST_MATH=ON
ERR! install running: cmake C:\Users\kpons\source\repos\jscheidelaar\pneumacision\node_modules\@u4\opencv-build\dist\opencv-4.5.5-d8111\opencv -G "Visual Studio 17 2022" -DCMAKE_INSTALL_PREFIX=C:\Users\kpons\source\repos\jscheidelaar\pneumacision\node_modules\@u4\opencv-build\dist\opencv-4.5.5-d8111\build -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_TYPES=Release -DBUILD_EXAMPLES=OFF -DBUILD_DOCS=OFF -DBUILD_TESTS=OFF -DBUILD_opencv_dnn=ON -DENABLE_FAST_MATH=ON -DBUILD_PERF_TESTS=OFF -DBUILD_JAVA=OFF -DBUILD_ZLIB=OFF -DCUDA_NVCC_FLAGS=--expt-relaxed-constexpr -DWITH_VTK=OFF -DOPENCV_ENABLE_NONFREE=ON -DOPENCV_EXTRA_MODULES_PATH=C:\Users\kpons\source\repos\jscheidelaar\pneumacision\node_modules\@u4\opencv-build\dist\opencv-4.5.5-d8111\opencv_contrib\modules -DBUILD_opencv_apps=OFF -DBUILD_opencv_aruco=OFF -DBUILD_opencv_bgsegm=OFF -DBUILD_opencv_bindings_generator=OFF -DBUILD_opencv_bioinspired=OFF -DBUILD_opencv_calib3d=ON -DBUILD_opencv_ccalib=OFF -DBUILD_opencv_core=ON -DBUILD_opencv_datasets=OFF -DBUILD_opencv_dnn=ON -DBUILD_opencv_dnn_objdetect=OFF -DBUILD_opencv_dpm=OFF -DBUILD_opencv_face=ON -DBUILD_opencv_features2d=ON -DBUILD_opencv_flann=ON -DBUILD_opencv_fuzzy=OFF -DBUILD_opencv_gapi=ON -DBUILD_opencv_hfs=OFF -DBUILD_opencv_highgui=ON -DBUILD_opencv_img_hash=ON -DBUILD_opencv_imgcodecs=ON -DBUILD_opencv_imgproc=ON -DBUILD_opencv_java_bindings_generator=OFF -DBUILD_opencv_js=OFF -DBUILD_opencv_line_descriptor=OFF -DBUILD_opencv_ml=ON -DBUILD_opencv_objc_bindings_generator=OFF -DBUILD_opencv_objdetect=ON -DBUILD_opencv_optflow=OFF -DBUILD_opencv_phase_unwrapping=OFF -DBUILD_opencv_photo=ON -DBUILD_opencv_python3=OFF -DBUILD_opencv_python_bindings_generator=OFF -DBUILD_opencv_python_tests=ON -DBUILD_opencv_reg=OFF -DBUILD_opencv_rgbd=OFF -DBUILD_opencv_saliency=OFF -DBUILD_opencv_shape=OFF -DBUILD_opencv_stereo=OFF -DBUILD_opencv_stitching=OFF -DBUILD_opencv_structured_light=OFF -DBUILD_opencv_superres=OFF -DBUILD_opencv_surface_matching=OFF -DBUILD_opencv_text=ON -DBUILD_opencv_tracking=ON -DBUILD_opencv_ts=OFF -DBUILD_opencv_video=ON -DBUILD_opencv_videoio=ON -DBUILD_opencv_videostab=ON -DBUILD_opencv_wechat_qrcode=OFF -DBUILD_opencv_world=OFF -DBUILD_opencv_xfeatures2d=ON -DBUILD_opencv_ximgproc=ON -DBUILD_opencv_xobjdetect=OFF -DBUILD_opencv_xphoto=OFF -DWITH_CUDA=ON -DWITH_CUDNN=ON -DOPENCV_DNN_CUDA=ON -DCUDA_FAST_MATH=ON
ERR! install in C:\Users\kpons\source\repos\jscheidelaar\pneumacision\node_modules\@u4\opencv-build\dist\opencv-4.5.5-d8111\build exited with code 1 (for more info, set '--loglevel silly')'

**Comment by UrielCh** [comment]
your error message is troncated.
