### ISSUE TITLE
opencv4nodejs install error on macos intel - binding.gyp not found

### ISSUE THREAD

**Issue by QingLeiLi** [UrielCh/opencv4nodejs#13]
opencv4nodejs install error on macos intel.
Is there something missing?

# Error Message

```
> @u4/opencv4nodejs@6.1.1 install /opencv-test/node_modules/@u4/opencv4nodejs
> node-gyp rebuild

gyp: binding.gyp not found (cwd: /opencv-test/node_modules/@u4/opencv4nodejs) while trying to load binding.gyp
```

*OpenCV version* : 4.5.4_4

*With OpenCV-contrib?* (extra modules): no

*OS*: MacOSX Intel

**Comment by rih28** [comment]
I am also having this issue.

**Comment by rih28** [comment]
Seems that node-gyp is trying to rebuild on install. I had this working around exactly 20 days ago so I am guessing that it may be to do with the last commit. My method to get it working on an intel Mac was quite convoluted at that time:

npm install --save @u4/opencv4nodejs
Add the script lines to the package.json
npm install -g node-gyp
inside the @u4/opencv4nodejs directory in node_modules rename _binding.gyp to binding.gyp
Go to root folder
npm run do-install

However, I can't get past the initial npm install now, and none of the switches seem to disable the node-gyp rebuild command (except --dry-run, which is just a series of logs to the console).

**Comment by UrielCh** [comment]
binding.gyp is hidden by default as _binding.gyp the build script copy it as binding.gyp during the custom build process.

**Comment by QingLeiLi** [comment]
@UrielCh hi, could u install the package successfully on Nodejs v12.20.1?
and what does the `custom build` mean?
I just install the package with `npm install @u4/opencv4nodejs`, but it does not work.

**Comment by UrielCh** [comment]
See opencv4nodejs/install/compileLib.ts

This script properly configure environment before calling node-gyp rebuild.

see:
```json
  "bin": {
    "build-opencv": "bin/install.js"
  },
```
in package.json

**Comment by UrielCh** [comment]
Version 6.1.2 is ready

**Comment by QingLeiLi** [comment]
@UrielCh Tanks for the replay and work.
I try to install the `@u4/opencv4nodejs@6.1.2`, but install script is broken.

```
> echo Use 'build-opencv rebuild' of (node bin/install.js rebuild) script to start node-gyp, use --help to check all options.

sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `echo Use 'build-opencv rebuild' of (node bin/install.js rebuild) script to start node-gyp, use --help to check all options.'
```

Maybe the `()` need `\`, like

```
echo Use 'build-opencv rebuild' of \(node bin/install.js rebuild\) script to start node-gyp, use --help to check all options.
```

**Comment by QingLeiLi** [comment]
I send a [PR](https://github.com/UrielCh/opencv4nodejs/pull/14).
Feel free to edit.

**Comment by UrielCh** [comment]
noooo, I need to made a new release :(

**Comment by UrielCh** [comment]
Is the original issue still exists ?

My Intel based MacOS is in a cupboard...

**Comment by QingLeiLi** [comment]
I will try again tonight, sorry for the delay replay.

**Comment by QingLeiLi** [comment]
@UrielCh The original issue has been fixed, the installation can be completed normally, thanks.
The next problem is that the compilation of opencv fails.
It seems that this library cannot use the opencv installed by brew. I will open a new issue after trying it.
