### ISSUE TITLE
BUILD : Not able to build @u4/opencv4nodejs throws error at 70%

### ISSUE THREAD

**Issue by hardikdiyora** [UrielCh/opencv4nodejs#15]
Hello @UrielCh and Friends

Following steps I followed:

1. mkdir test
2. cd test
3. Run command: npm init -y
4. Run command: npm install --save @u4/opencv4nodejs
5. Run command: ./node_modules/.bin/build-opencv build
6. It started building with progress percentages (%).
7. And at last It throws error. starting and end logs I have attached below. 

Can you suggest something here to solve? 

# It started logging like below 

info config no opencv4nodejs section found in /Users/bob/test/package.json
info init no openCV version given using default verison 4.5.4
info init Workdir will be: /Users/bob/test/node_modules/@u4/opencv-build/opencv-4.5.4
info install Using openCV 4.5.4
info install Using lib dir: /Users/bob/test/node_modules/@u4/opencv-build/opencv-4.5.4/build/lib
info install if you want to use an own OpenCV installation set OPENCV4NODEJS_DISABLE_AUTOBUILD
info readAutoBuildFile file does not exists: /Users/bob/test/node_modules/@u4/opencv-build/opencv-4.5.4/auto-build.json
info install 
info install running install script...
info install 
info install opencv version: 4.5.4
info install with opencv contrib: yes
info install custom build flags: < none >
info install 
info install executing: git --version
info install git Version 2.32.0 found
info install executing: cmake --version
info install cmake Version 3.22.3 found
info install installing opencv version 4.5.4 into directory: /Users/bob/test/node_modules/@u4/opencv-build/opencv-4.5.4
info install Cleaning old build, src, contrib-src directories
info install git clone https://github.com/opencv/opencv_contrib.git
remote: Enumerating objects: 3740, done.
remote: Counting objects: 100% (3740/3740), done.
remote: Compressing objects: 100% (3151/3151), done.
remote: Total 3740 (delta 664), reused 2081 (delta 341), pack-reused 0
Note: switching to '2bc3e1a169afd2675ef68221176f32cc0ea5427a'.

And then after some minutes of positive progress below:

# Error Message

[ 70%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/src/tensor.cpp.o  
[ 70%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/vulkan/vk_functions.cpp.o 
[ 70%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/vulkan/vk_loader.cpp.o  
[ 70%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx.cpp.o  
[ 70%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx2.cpp.o  
[ 70%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/int8layers/layers_common.avx2.cpp.o  
[ 70%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx512_skx.cpp.o
[ 70%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/int8layers/layers_common.avx512_skx.cpp.o
[ 70%] Linking CXX shared library ../../lib/libopencv_dnn.dylib
[ 70%] Built target opencv_dnn
make: *** [all] Error 2
ERR! Compilation failed, previous calls:
%s rimraf /Users/bob/test/node_modules/@u4/opencv-build/opencv-4.5.4/build /Users/bob/test/node_modules/@u4/opencv-build/opencv-4.5.4/opencv /Users/bob/test/node_modules/@u4/opencv-build/opencv-4.5.4/opencv_contrib
ERR! Compilation failed, previous calls:
%s mkdir -p /Users/bob/test/node_modules/@u4/opencv-build/opencv-4.5.4/build
ERR! Compilation failed, previous calls:
%s cd /Users/bob/test/node_modules/@u4/opencv-build/opencv-4.5.4
ERR! Compilation failed, previous calls:
%s git clone --quiet -b 4.5.4 --single-branch --depth 1 --progress https://github.com/opencv/opencv_contrib.git
ERR! Compilation failed, previous calls:
%s git clone --quiet -b 4.5.4 --single-branch --depth 1 --progress https://github.com/opencv/opencv.git
ERR! Compilation failed, previous calls:
%s cd /Users/bob/test/node_modules/@u4/opencv-build/opencv-4.5.4/build
ERR! Compilation failed, previous calls:
%s cmake /Users/bob/test/node_modules/@u4/opencv-build/opencv-4.5.4/opencv -DCMAKE_INSTALL_PREFIX=/Users/bob/test/node_modules/@u4/opencv-build/opencv-4.5.4/build -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF -DBUILD_DOCS=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_JAVA=OFF -DCUDA_NVCC_FLAGS=--expt-relaxed-constexpr -DBUILD_opencv_apps=OFF -DBUILD_opencv_aruco=OFF -DBUILD_opencv_bgsegm=OFF -DBUILD_opencv_bioinspired=OFF -DBUILD_opencv_ccalib=OFF -DBUILD_opencv_datasets=OFF -DBUILD_opencv_dnn_objdetect=OFF -DBUILD_opencv_dpm=OFF -DBUILD_opencv_fuzzy=OFF -DBUILD_opencv_hfs=OFF -DBUILD_opencv_java_bindings_generator=OFF -DBUILD_opencv_js=OFF -DBUILD_opencv_img_hash=OFF -DBUILD_opencv_line_descriptor=OFF -DBUILD_opencv_optflow=OFF -DBUILD_opencv_phase_unwrapping=OFF -DBUILD_opencv_python3=OFF -DBUILD_opencv_python_bindings_generator=OFF -DBUILD_opencv_reg=OFF -DBUILD_opencv_rgbd=OFF -DBUILD_opencv_saliency=OFF -DBUILD_opencv_shape=OFF -DBUILD_opencv_stereo=OFF -DBUILD_opencv_stitching=OFF -DBUILD_opencv_structured_light=OFF -DBUILD_opencv_superres=OFF -DBUILD_opencv_surface_matching=OFF -DBUILD_opencv_ts=OFF -DBUILD_opencv_xobjdetect=OFF -DBUILD_opencv_xphoto=OFF -DWITH_VTK=OFF -DOPENCV_ENABLE_NONFREE=ON -DOPENCV_EXTRA_MODULES_PATH=/Users/bob/test/node_modules/@u4/opencv-build/opencv-4.5.4/opencv_contrib/modules
ERR! install running: make install -j8
ERR! install in /Users/bob/test/node_modules/@u4/opencv-build/opencv-4.5.4/build exited with code 2 (for more info, set '--loglevel silly')'

## Common things to know

*OpenCV version* : 4.5.4

*With OpenCV-contrib?* (extra modules): NO

*OS*: Windows 7 / 8 / 10? / MacOSX? / Ubuntu? MacOSX

*node version*: v16.13.2

*npm version*:  8.1.2

**Comment by UrielCh** [comment]
Apple Silicon or intel ?

**Comment by hardikdiyora** [comment]
Processor: 2,7 GHz Quad-Core Intel Core i7
Graphics: Intel Iris Plus Graphics 655 1536 MB
Memory: 16 GB 2133 MHz LPDDR3

**Comment by UrielCh** [comment]
lucky you are, I have to work on a Mac for the next 10 days, and I have also an error in
 Built target opencv_dnn

**Comment by hardikdiyora** [comment]
@UrielCh any luck on how to solve this build error?

**Comment by UrielCh** [comment]
can you try to use the previous minor build?

I think something broke recently on Mac build.

**Comment by UrielCh** [comment]
no answer, closing this post.
