### ISSUE TITLE
Implementing TrackerNano

### ISSUE THREAD

**Issue by figamore** [UrielCh/opencv4nodejs#164]
Would it be feasible to implement OpenCV's TrackerNano? I'm willing to implement it, but some pointers on which files to modify or add would be helpful. Would it be similar to how GOTURN was implemented?

**Comment by UrielCh** [comment]
I'm now updating the project to use N-API intead of Nan , I can not assit you rigth now.

**Comment by figamore** [comment]
Just implemented it on #165. Working great!

**Comment by UrielCh** [comment]
PR commented + test in progess

**Comment by UrielCh** [comment]
Bye the way CI failed.
