### ISSUE TITLE
Why cvloader.js remove the node suffix path name?

### ISSUE THREAD

**Issue by ht-jo** [UrielCh/opencv4nodejs#172]
Hello. I'm conflicted the problem of `require path` in cvloader.

I know the opencv4nodejs build result exist in `build/Release/opencv4nodejs.node`, and there was no problem in the past when 6 version.

I recently installed the latest version(7.1.2) of opencv4nodejs, there are so many good changes. But I don't know why this tries to find the build result of no suffix name(`build/Release/opencv4nodejs`). Of course, there should be a reason you have to add [this code](https://github.com/UrielCh/opencv4nodejs/blob/master/cjs/lib/cvloader.js#L52). Could you explain why it tries to import the file name of the no suffix `.node`?

Thank you.

**Comment by ht-jo** [comment]
There was what I misunderstood about commonjs setting in jest.config. I'm sorry!

**Comment by ArvenCo** [comment]
Hi, how did you fix this? I use Playwright, and I want to know what configuration you applied.
