### ISSUE TITLE
Mac M3 installation @ u4/opencv4nodejs failed

### ISSUE THREAD

**Issue by code565** [UrielCh/opencv4nodejs#175]
My operational steps

`
brew update 
brew install opencv@4   
brew link --force opencv@4    
 nano ~/.bash_profile    

export OPENCV4NODEJS_DISABLE_AUTOBUILD=1
export OPENCV_LIB_DIR=/opt/homebrew/Cellar/opencv/4.10.0_18/lib
export OPENCV_BIN_DIR=/opt/homebrew/Cellar/opencv/4.10.0_18/bin
export OPENCV_INCLUDE_DIR=/opt/homebrew/Cellar/opencv/4.10.0_18/include/opencv4

source ~/.bash_profile

npm install -g @u4/opencv4nodejs
`
**Failure message**
`npm error code 1
npm error path /Users/benben/.nvm/versions/node/v20.18.1/lib/node_modules/@u4/opencv4nodejs
npm error command failed
npm error command sh -c node-gyp rebuild
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.3.1
npm error gyp info using node@20.18.1 | darwin | arm64
npm error gyp info find Python using Python version 3.10.0 found at "/Users/benben/.pyenv/versions/3.10.0/bin/python3"
npm error gyp info spawn /Users/benben/.pyenv/versions/3.10.0/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args '/Users/benben/.nvm/versions/node/v20.18.1/lib/node_modules/@u4/opencv4nodejs/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/benben/.nvm/versions/node/v20.18.1/lib/node_modules/@u4/opencv4nodejs/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/benben/.nvm/versions/node/v20.18.1/lib/node_modules/@u4/opencv4nodejs/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/benben/Library/Caches/node-gyp/20.18.1/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/Users/benben/Library/Caches/node-gyp/20.18.1',
npm error gyp info spawn args '-Dnode_gyp_dir=/Users/benben/.nvm/versions/node/v20.18.1/lib/node_modules/@u4/opencv4nodejs/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/Users/benben/Library/Caches/node-gyp/20.18.1/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/Users/benben/.nvm/versions/node/v20.18.1/lib/node_modules/@u4/opencv4nodejs',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp: Undefined variable & in binding.gyp while trying to load binding.gyp
npm error gyp ERR! configure error 
npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
npm error gyp ERR! stack at ChildProcess.<anonymous> (/Users/benben/.nvm/versions/node/v20.18.1/lib/node_modules/@u4/opencv4nodejs/node_modules/node-gyp/lib/configure.js:317:18)
npm error gyp ERR! stack at ChildProcess.emit (node:events:518:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm error gyp ERR! System Darwin 23.5.0
npm error gyp ERR! command "/Users/benben/.nvm/versions/node/v20.18.1/bin/node" "/Users/benben/.nvm/versions/node/v20.18.1/lib/node_modules/@u4/opencv4nodejs/node_modules/.bin/node-gyp" "rebuild"
npm error gyp ERR! cwd /Users/benben/.nvm/versions/node/v20.18.1/lib/node_modules/@u4/opencv4nodejs
npm error gyp ERR! node -v v20.18.1
npm error gyp ERR! node-gyp -v v10.3.1
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: /Users/benben/.npm/_logs/2024-12-28T10_38_32_523Z-debug-0.log`

**Comment by cory-weiner** [comment]
Did you find a solution to this? I'm having troubles installing on M3 Max chip
