### ISSUE TITLE
Cannot compile with ImplicitAny option in TypeScript

### ISSUE THREAD

**Issue by Shin-Ogata** [UrielCh/opencv4nodejs#19]
Thank you for your great job.
I found that I can't build with the ImplicitAny option in TypeScript.

# Condition
As the manual says, I'm using the module like this.
```ts
import * as cv from '@u4/opencv4nodejs';
export { cv };
```

And I prepared `tsconfig.json` as follows.
```json
{
  "compilerOptions": {
    "module": "esnext",
    "target": "es2020",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "outDir": "built",
    "rootDir": "src"
  },
  "include": [
    "src/**/*"
  ]
}
```

# Error Message
```sh
$ tsc -p ./tsconfig.json
node_modules/@u4/opencv4nodejs/typings/group/highgui.d.ts:46:18 - error TS7010: 'moveWindow', which lacks return-type annotation, implicitly has an 'any' return type.

46 export  function moveWindow(winname: string, x: number, y: number);
                    ~~~~~~~~~~

node_modules/@u4/opencv4nodejs/typings/group/highgui.d.ts:59:18 - error TS7010: 'namedWindow', which lacks return-type annotation, implicitly has an 'any' return type.

59 export  function namedWindow(winname: string, flags?: number);
                    ~~~~~~~~~~~
```
# Cause of the problem
This issue is caused by the undefined return values for `moveWindow` and` namedWindow` defined in `highgui.d.ts`.
- https://github.com/UrielCh/opencv4nodejs/blob/master/typings/group/highgui.d.ts#L46
- https://github.com/UrielCh/opencv4nodejs/blob/master/typings/group/highgui.d.ts#L59

It seems that the problem can be solved by modifying it as follows.

```ts
export function moveWindow(winname: string, x: number, y: number): void;

export function namedWindow(winname: string, flags?: number): void;
```

Thanks a lot.

----

*OpenCV version* (example 3.4.1): 4.5.4

*With OpenCV-contrib?* (extra modules): no

*OS*: Windows 11

**Comment by UrielCh** [comment]
Fixed.

**Comment by UrielCh** [comment]
release done
