### ISSUE TITLE
How to add eigenFace module ?

### ISSUE THREAD

**Issue by Aeryax** [UrielCh/opencv4nodejs#22]
Hello nice work ! My build work perfectly but I wonder how to add eigenFace module ? I tried with :
` .\node_modules\.bin\build-opencv --flags "-DWITH_EIGEN=ON" rebuild`

Without module, I have this error trying using it :
`opencv4nodejs_1EigenFaceRecognizer is not a constructor
    err: {
      "type": "TypeError",
      "message": "opencv4nodejs_1.EigenFaceRecognizer is not a constructor"
      }`

# Manual Build - Environment Information

*OpenCV version* (example 3.4.1): 4.5.5

*With OpenCV-contrib?* (extra modules): yes

*OS*: Windows 7 / 8 / 10? / MacOSX? / Ubuntu? Windows

**Comment by UrielCh** [comment]
I did not use EigenFaceRecognizer yet.
and -DWITH_EIGEN  is not part of the default build flag, so adding --flags "-DWITH_EIGEN=ON" looks nice.

No time to check that now.

look in `EigenFaceRecognizer.cc`:

#ifdef HAVE_OPENCV_FACE

then in `opencv_modules.h`
#ifdef OPENCV4NODEJS_FOUND_LIBRARY_FACE
#define HAVE_OPENCV_FACE
#endif

but only for openCV < 3.2.0

I think HAVE_OPENCV_FACE is part of the automatic Opencv generated flag.

I can not dig more than that this week.

**Comment by Aeryax** [comment]
Hello thanks for your answer. After further investigation, it works now using 4.5.3. It looks like 4.5.4 doesn't have face module anymore.

Face documentation is last found on 4.5.3 : https://docs.opencv.org/4.5.3/d3/dc8/face_8hpp.html
Probably an issue on OpenCV side.

**Comment by UrielCh** [comment]
So eigenFace was removed in OpenCV 4.5.4.
I may add an error message for that case.
