### ISSUE TITLE
Fail to load when deploying to another computer after building for electron

### ISSUE THREAD

**Issue by Laudamus** [UrielCh/opencv4nodejs#29]
Thanks for making a good branch.

I was very happy that I installed @u4/opencv4nodejs and succeeded in building opencv 3.4.6 for electron.

But when I build the electron app and deploy it to another computer, the module cannot be loaded.

Could you please help me with this?

# Error message
![image](https://user-images.githubusercontent.com/23294514/167114033-1cf30a50-e2ac-4bb0-9f73-c1adada8d167.png)

# Reproduce the error
After building for electron, change the project folder name to something else and run it

# Thought of cause
1. When I modified the buildRoot in the auto-build.json file to match the changed project folder name, it was loaded.
2. So, I think the logic to set the path of the opencv-build folder to an absolute path is a problem.
3. I believe this problem can be solved by setting the path of the opencv-build folder to a relative path, but I don't know how.

**Comment by UrielCh** [comment]
I gonna have issues assisting you since I do not use electron, I only made some patches to make it borks once, please refer to 
https://github.com/UrielCh/opencv-electron

**Comment by Laudamus** [comment]
@UrielCh Wow. I found a hint in the README of the link you gave me.
It was solved by finding the opencv binary directory and registering it in process.env.path.
It seems to be finished by finding the deployed computer path and setting it automatically.

Thanks for your help.

**Comment by UrielCh** [comment]
nice

**Comment by thiscantbeserious** [comment]
I have to say that this is actually a bad workaround and should be solved within cvloader.js/ts instead.

By that I mean that it should resolve into an relative path if autobuild is enabled and skip the PATH check.

This will enable one to ship opencv-build together with their bundles not just in Windows.

Currently it discards/errors out because its a) an absolute path b) because it's not within the path.
