### ISSUE TITLE
Cannot build on macOs

### ISSUE THREAD

**Issue by SBRKH** [UrielCh/opencv4nodejs#30]
Hello,

I'm trying to install opencv4nodejs since few days but I've always an error message (see below).

To reproduce the steps : 
1. npm install --save @u4/opencv4nodejs
2. add to my package.json scripts

> {
> "install_arm64": "build-opencv --version 4.5.4 --flag=\"-DCMAKE_SYSTEM_PROCESSOR=arm64 -DCMAKE_OSX_ARCHITECTURES=arm64\" build",
>       "install_4.5.5_cuda": "build-opencv --version 4.5.5 --flags=\"-DWITH_CUDA=ON -DWITH_CUDNN=ON -DOPENCV_DNN_CUDA=ON -DCUDA_FAST_MATH=ON\" build",
>       "do-install": "build-opencv build"
> }
3. npm run do-install (i also tried the others script but no one work)

If anyone have an idea...
Thank you

# Error Message
info install Spawning in directory:/Users/Documents/Hobbies/sictures/back/node_modules/@u4/opencv4nodejs node-gyp process: node-gyp build --jobs max --release 
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@18.0.0 | darwin | x64
gyp ERR! build error 
gyp ERR! stack Error: You must run `node-gyp configure` first!
gyp ERR! stack     at ReadFileContext.<anonymous> 
gyp ERR! stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:319:13)
gyp ERR! System Darwin 21.4.0
gyp ERR! node -v v18.0.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok 
gyp ERR! stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:319:13)
gyp ERR! System Darwin 21.4.0
gyp ERR! command "/usr/local/Cellar/node/18.0.0/bin/node" "/Users/Documents/Hobbies/sictures/back/node_modules/.bin/node-gyp" "build" "--jobs" "max" "--release"
gyp ERR! cwd /Users/Documents/Hobbies/sictures/back/node_modules/@u4/opencv4nodejs
gyp ERR! node -v v18.0.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok 

    at ChildProcess.exithandler (node:child_process:387:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1090:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:715:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'node-gyp build --jobs max --release '
}
.4.1
ERR! install gyp ERR! not ok 
ERR! install  return code: 1

*OpenCV version* : 4.5.4

*With OpenCV-contrib?* (extra modules): no

*OS*: MacOSX

**Comment by UrielCh** [comment]
adding some script in your package.json is nice, calling them is better 😄 

what did you table to get this error?

**Comment by SBRKH** [comment]
> adding some script in your package.json is nice, calling them is better 😄
> 
> what did you table to get this error?

Hi !

Thank you for your reply. I tried each script.
Firstly "install_4.5.5_cuda" but I read on some issue that we shouldn't use 4.5.5 on MacOSX so secondly "install_arm64" which doesn't work. Then i tried "do-install" who give me this error.

**Comment by UrielCh** [comment]
why did you try the cuda build on an Mac M1 ?
cuda == nvidia

**Comment by attilaaronnagy** [comment]
I also can not build it on macOS. Don't know what can be the problem.

`ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/imgproc/imgprocConstants.o] Error 1
ERR! install In file included from ../cc/imgproc/MatImgproc.cc:1:
ERR! install In file included from ../cc/opencv_modules.h:1:
ERR! install ../cc/macros.h:2:10: fatal error: 'opencv2/core.hpp' file not found
ERR! install #include <opencv2/core.hpp>
ERR! install          ^~~~~~~~~~~~~~~~~~
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/core/Point.o] Error 1
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/core/Vec.o] Error 1
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/core/RotatedRect.o] Error 1
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/ExternalMemTracking.o] Error 1
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/CustomMatAllocator.o] Error 1
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/imgproc/imgproc.o] Error 1
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/core/core.o] Error 1
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/imgproc/MatImgproc.o] Error 1
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/core/Mat.o] Error 1
ERR! install 1 error generated.
ERR! install make: *** [Release/obj.target/opencv4nodejs/cc/opencv4nodejs.o] Error 1
ERR! install gyp ERR! build error
ERR! install gyp ERR! stack Error: `make` failed with exit code: 2
ERR! install gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
ERR! install gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
ERR! install gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
ERR! install gyp ERR! System Darwin 21.4.0
ERR! install gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--jobs" "max" "--release"
ERR! install gyp ERR! cwd /Users/attilaaronnagy/Desktop/temporary/nodecam/webcam_/node_modules/@u4/opencv4nodejs
ERR! install gyp ERR! node -v v16.15.0
ERR! install gyp ERR! node-gyp -v v9.0.0
ERR! install gyp ERR! not ok
ERR! install  return code: 1`

**Comment by SBRKH** [comment]
> why did you try the cuda build on an Mac M1 ? cuda == nvidia M1 == Apple

Firstly I was just trying to follow the step from the README then I figure out that cuda wasn't for my mac (lol) so I try the others.

**Comment by UrielCh** [comment]
I'm working on Mac build, and I think the issue come from openCV contribution repository.
ffmpeg 5.X contains breaking changes,

**Comment by SBRKH** [comment]
Hello,

I tried to rebuild as mentioned in #32 and apparently it solved my problem.
I close the ticket.
