### ISSUE TITLE
Cannot build bindings with error "You must run node-gyp configure first!"

### ISSUE THREAD

**Issue by skibon02** [UrielCh/opencv4nodejs#32]
I got error trying to install opencv bindings on node js. And i had the same error with disabled and enabled autobuild, it asks me to run node-gyp configure first in both cases. I guess i shouldn't do it manually, because if i do, i get another errors with include directories. I did the following steps on two different computers with Ubuntu 20 and 22:

- `npm install --save @u4/opencv4nodejs`

- add scripts to package.json:

```
  "scripts": {
    "install_arm64": "build-opencv --version 4.5.4 --flag=\"-DCMAKE_SYSTEM_PROCESSOR=arm64 -DCMAKE_OSX_ARCHITECTURES=arm64\" build",
    "install_4.5.5_cuda": "build-opencv --version 4.5.5 --flags=\"-DWITH_CUDA=ON -DWITH_CUDNN=ON -DOPENCV_DNN_CUDA=ON -DCUDA_FAST_MATH=ON\" build",
    "do-install": "build-opencv build",
  }
```

- `npm run install_4.5.5_cuda`
or in other case
- add configurations to disable autobuild:
```
  "opencv4nodejs": {
    "disableAutoBuild": 1,
    "opencvIncludeDir": "/home/user/OpenCV/4.5.3/opencv-4.5.3/include",
    "opencvLibDir": "/home/user/OpenCV/4.5.3/opencv-4.5.3/release/lib",
    "opencvBinDir": "/home/user/OpenCV/4.5.3/opencv-4.5.3/release/bin"
  },
```

- `npm run install_4.5.5_cuda`

# Error Message
You must run `node-gyp configure` first!

# Auto Build - Full Error Log

info install writing auto-build file into directory: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/auto-build.json
info install 
info install Found the following libs:
info install calib3d: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_calib3d.so.4.5.5
info install core: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_core.so.4.5.5
info install dnn: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_dnn.so.4.5.5
info install features2d: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_features2d.so.4.5.5
info install flann: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_flann.so.4.5.5
info install gapi: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_gapi.so.4.5.5
info install highgui: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_highgui.so.4.5.5
info install imgcodecs: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_imgcodecs.so.4.5.5
info install imgproc: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_imgproc.so.4.5.5
info install ml: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_ml.so.4.5.5
info install objdetect: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_objdetect.so.4.5.5
info install photo: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_photo.so.4.5.5
info install video: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_video.so.4.5.5
info install videoio: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_videoio.so.4.5.5
info install videostab: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_videostab.so.4.5.5
info install face: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_face.so.4.5.5
info install text: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_text.so.4.5.5
info install tracking: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_tracking.so.4.5.5
info install xfeatures2d: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_xfeatures2d.so.4.5.5
info install ximgproc: /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/lib/libopencv_ximgproc.so.4.5.5
info defines 
info defines Setting the following defines:
info defines OPENCV4NODEJS_FOUND_LIBRARY_CALIB3D     OPENCV4NODEJS_FOUND_LIBRARY_CORE        OPENCV4NODEJS_FOUND_LIBRARY_DNN         
info defines OPENCV4NODEJS_FOUND_LIBRARY_FEATURES2D  OPENCV4NODEJS_FOUND_LIBRARY_FLANN       OPENCV4NODEJS_FOUND_LIBRARY_GAPI        
info defines OPENCV4NODEJS_FOUND_LIBRARY_HIGHGUI     OPENCV4NODEJS_FOUND_LIBRARY_IMGCODECS   OPENCV4NODEJS_FOUND_LIBRARY_IMGPROC     
info defines OPENCV4NODEJS_FOUND_LIBRARY_ML          OPENCV4NODEJS_FOUND_LIBRARY_OBJDETECT   OPENCV4NODEJS_FOUND_LIBRARY_PHOTO       
info defines OPENCV4NODEJS_FOUND_LIBRARY_VIDEO       OPENCV4NODEJS_FOUND_LIBRARY_VIDEOIO     OPENCV4NODEJS_FOUND_LIBRARY_VIDEOSTAB   
info defines OPENCV4NODEJS_FOUND_LIBRARY_FACE        OPENCV4NODEJS_FOUND_LIBRARY_TEXT        OPENCV4NODEJS_FOUND_LIBRARY_TRACKING    
info defines OPENCV4NODEJS_FOUND_LIBRARY_XFEATURES2D OPENCV4NODEJS_FOUND_LIBRARY_XIMGPROC    
info install 
info install Setting the following includes:
info includes /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/include
info includes /home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build/include/opencv4
info libs 
info libs Setting lib from -L/home/user/skibon/opencv-node/node_modules/@u4/opencv-build/opencv-4.5.5-8b031/build : lib, -lopencv_calib3d, -lopencv_core, -lopencv_dnn, -lopencv_features2d, -lopencv_flann, -lopencv_gapi, -lopencv_highgui, -lopencv_imgcodecs, -lopencv_imgproc, -lopencv_ml, -lopencv_objdetect, -lopencv_photo, -lopencv_video, -lopencv_videoio, -lopencv_videostab, -lopencv_face, -lopencv_text, -lopencv_tracking, -lopencv_xfeatures2d, -lopencv_ximgproc, lib
info install Spawning in directory:/home/user/skibon/opencv-node/node_modules/@u4/opencv4nodejs node-gyp process: node-gyp build --jobs max --release 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@18.1.0 | linux | x64
gyp ERR! build error 
gyp ERR! stack Error: You must run `node-gyp configure` first!
gyp ERR! stack     at ReadFileContext.<anonymous> (/home/user/skibon/opencv-node/node_modules/node-gyp/lib/build.js:43:20)
gyp ERR! stack     at ReadFileContext.callback (/home/user/skibon/opencv-node/node_modules/graceful-fs/graceful-fs.js:123:16)
gyp ERR! stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:319:13)
gyp ERR! System Linux 5.13.0-41-generic
gyp ERR! command "/home/user/.nvm/versions/node/v18.1.0/bin/node" "/home/user/skibon/opencv-node/node_modules/.bin/node-gyp" "build" "--jobs" "max" "--release"
gyp ERR! cwd /home/user/skibon/opencv-node/node_modules/@u4/opencv4nodejs
gyp ERR! node -v v18.1.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
error:  Error: Command failed: node-gyp build --jobs max --release 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@18.1.0 | linux | x64
gyp ERR! build error 
gyp ERR! stack Error: You must run `node-gyp configure` first!
gyp ERR! stack     at ReadFileContext.<anonymous> (/home/user/skibon/opencv-node/node_modules/node-gyp/lib/build.js:43:20)
gyp ERR! stack     at ReadFileContext.callback (/home/user/skibon/opencv-node/node_modules/graceful-fs/graceful-fs.js:123:16)
gyp ERR! stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:319:13)
gyp ERR! System Linux 5.13.0-41-generic
gyp ERR! command "/home/user/.nvm/versions/node/v18.1.0/bin/node" "/home/user/skibon/opencv-node/node_modules/.bin/node-gyp" "build" "--jobs" "max" "--release"
gyp ERR! cwd /home/user/skibon/opencv-node/node_modules/@u4/opencv4nodejs
gyp ERR! node -v v18.1.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 

    at ChildProcess.exithandler (node:child_process:387:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1090:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:715:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'node-gyp build --jobs max --release '
}
ERR! install node-gyp failed and return Error Command failed: node-gyp build --jobs max --release 
ERR! install gyp info it worked if it ends with ok
ERR! install gyp info using node-gyp@9.0.0
ERR! install gyp info using node@18.1.0 | linux | x64
ERR! install gyp ERR! build error 
ERR! install gyp ERR! stack Error: You must run `node-gyp configure` first!
ERR! install gyp ERR! stack     at ReadFileContext.<anonymous> (/home/user/skibon/opencv-node/node_modules/node-gyp/lib/build.js:43:20)
ERR! install gyp ERR! stack     at ReadFileContext.callback (/home/user/skibon/opencv-node/node_modules/graceful-fs/graceful-fs.js:123:16)
ERR! install gyp ERR! stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:319:13)
ERR! install gyp ERR! System Linux 5.13.0-41-generic
ERR! install gyp ERR! command "/home/user/.nvm/versions/node/v18.1.0/bin/node" "/home/user/skibon/opencv-node/node_modules/.bin/node-gyp" "build" "--jobs" "max" "--release"
ERR! install gyp ERR! cwd /home/user/skibon/opencv-node/node_modules/@u4/opencv4nodejs
ERR! install gyp ERR! node -v v18.1.0
ERR! install gyp ERR! node-gyp -v v9.0.0
ERR! install gyp ERR! not ok 
ERR! install  return code: 1

# Manual Build - Environment Information

*OpenCV version:* tried 4.5.3 and 4.5.5 with CUDA 11.4 and 11.6

*With OpenCV-contrib?*: yes

*OS*: Ubuntu
*Node version*: 18.0.0
*npm version*: 8.8.0

**Comment by Ac3NiNjA** [comment]
Try the `rebuild` command instead.
`build-opencv rebuild`, as suggested here: https://github.com/UrielCh/opencv4nodejs/issues/28#issuecomment-1118959914

There is also a `configure` command, which I assume might also solve your issue.
You can run `build-opencv` alone to list all commands/flags.

**Comment by skibon02** [comment]
Alright, i found a way to fix this issue. 
here is another error log when i use `rebuild` or `configure` option for `build-opencv` command:

<details>
  <summary>Error log:</summary>
  
ERR! install node-gyp failed and return Error Command failed: node-gyp rebuild --jobs max --release 
ERR! install gyp info it worked if it ends with ok
ERR! install gyp info using node-gyp@9.0.0
ERR! install gyp info using node@18.1.0 | linux | x64
ERR! install gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
ERR! install gyp info spawn /usr/bin/python3
ERR! install gyp info spawn args [
ERR! install gyp info spawn args   '/home/user/skibon/opencv-node/node_modules/node-gyp/gyp/gyp_main.py',
ERR! install gyp info spawn args   'binding.gyp',
ERR! install gyp info spawn args   '-f',
ERR! install gyp info spawn args   'make',
ERR! install gyp info spawn args   '-I',
ERR! install gyp info spawn args   '/home/user/skibon/opencv-node/node_modules/@u4/opencv4nodejs/build/config.gypi',
ERR! install gyp info spawn args   '-I',
ERR! install gyp info spawn args   '/home/user/skibon/opencv-node/node_modules/node-gyp/addon.gypi',
ERR! install gyp info spawn args   '-I',
ERR! install gyp info spawn args   '/home/user/.cache/node-gyp/18.1.0/include/node/common.gypi',
ERR! install gyp info spawn args   '-Dlibrary=shared_library',
ERR! install gyp info spawn args   '-Dvisibility=default',
ERR! install gyp info spawn args   '-Dnode_root_dir=/home/user/.cache/node-gyp/18.1.0',
ERR! install gyp info spawn args   '-Dnode_gyp_dir=/home/user/skibon/opencv-node/node_modules/node-gyp',
ERR! install gyp info spawn args   '-Dnode_lib_file=/home/user/.cache/node-gyp/18.1.0/<(target_arch)/node.lib',
ERR! install gyp info spawn args   '-Dmodule_root_dir=/home/user/skibon/opencv-node/node_modules/@u4/opencv4nodejs',
ERR! install gyp info spawn args   '-Dnode_engine=v8',
ERR! install gyp info spawn args   '--depth=.',
ERR! install gyp info spawn args   '--no-parallel',
ERR! install gyp info spawn args   '--generator-output',
ERR! install gyp info spawn args   'build',
ERR! install gyp info spawn args   '-Goutput_dir=.'
ERR! install gyp info spawn args ]
ERR! install Debugger listening on ws://127.0.0.1:46691/df5ee921-17ad-4bba-9150-654ac8d4532b
ERR! install For help, see: https://nodejs.org/en/docs/inspector
ERR! install Debugger attached.
ERR! install Waiting for the debugger to disconnect...
ERR! install gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
ERR! install gyp ERR! configure error 
ERR! install gyp ERR! stack Error: `gyp` failed with exit code: 1
ERR! install gyp ERR! stack     at ChildProcess.onCpExit (/home/user/skibon/opencv-node/node_modules/node-gyp/lib/configure.js:261:16)
ERR! install gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
ERR! install gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
ERR! install gyp ERR! System Linux 5.13.0-41-generic
ERR! install gyp ERR! command "/home/user/.nvm/versions/node/v18.1.0/bin/node" "/home/user/skibon/opencv-node/node_modules/.bin/node-gyp" "rebuild" "--jobs" "max" "--release"
ERR! install gyp ERR! cwd /home/user/skibon/opencv-node/node_modules/@u4/opencv4nodejs
ERR! install gyp ERR! node -v v18.1.0
ERR! install gyp ERR! node-gyp -v v9.0.0
ERR! install gyp ERR! not ok 
ERR! install  return code: 1
</details>
The most important lines here are:

- ERR! install gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp

- ERR! install gyp ERR! configure error

So the solution that worked for me is simply manually replace 11 and 12 lines in `node_modules/@u4/opencv4nodejs/binding.gyp`:
```
"<!(node -e \"require('nan')\")",
"<!(node -e \"require('native-node-utils')\")"
```
were replaced with
```
"../../nan",
"../../native-node-utils/src"
```
And finally, i found the problem in my setup: i used a VS code with Auto Attach option: always, so, i guess, some redundant lines were added in the output of  node -e \"require('nan')\" command:
```
Debugger attached.
node_modules/nan
Waiting for the debugger to disconnect...
```

**Comment by UrielCh** [comment]
so it is fixed and that is not a common error. No FAQ update.
