### ISSUE TITLE
error TS7051 occurs with noImplicitAny option in TypeScript

### ISSUE THREAD

**Issue by Shin-Ogata** [UrielCh/opencv4nodejs#33]
Thank you for the continuous improvement.
I found that even the latest version (v6.1.5) cannot be built with TypeScript's ImplicitAny option.

# Condition
As the manual says, I'm using the module like this.
```ts
import * as cv from '@u4/opencv4nodejs';
export { cv };
```

And I prepared `tsconfig.json` as follows.
```json
{
  "compilerOptions": {
    "module": "esnext",
    "target": "es2020",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "outDir": "built",
    "rootDir": "src"
  },
  "include": [
    "src/**/*"
  ]
}
```

# Error Message
```sh
$ tsc -p ./tsconfig.json
node_modules/@u4/opencv4nodejs/typings/Facemark.d.ts:14:30 - error TS7051: Parameter has a name but no type. Did you mean 'arg0: any[]'?

14   setFaceDetector(callback: (...any) => any): boolean;
                                ~~~~~~


Found 1 error in node_modules/@u4/opencv4nodejs/typings/Facemark.d.ts:14
```

# Cause of the problem
I think the following changes are appropriate in [Facemark.d.ts](https://github.com/UrielCh/opencv4nodejs/blob/master/typings/Facemark.d.ts#L14).

```diff
-  setFaceDetector(callback: (...any) => any): boolean;
+  setFaceDetector(callback: (...args: any[]) => any): boolean;

```

Thanks.

----
*@u4/opencv4nodejs version*: 6.1.5

*OpenCV version* (example 3.4.1): 4.5.5

*With OpenCV-contrib?* (extra modules): no

*OS*: Windows 11

**Comment by Shin-Ogata** [comment]
Thank you for your great activities.
However, due to this issue, it is not yet adopted in our TypeScript project.
(On the other hand, we cannot use v6.1.4 and v6.1.3 or older because #19 and #26 exist.)

So if possible, we would be very grateful if you could release a fixed version of this issue.

**Comment by UrielCh** [comment]
@u4/opencv4nodejs@6.1.6 is out just for you.

You owe me feedback, from now.

**Comment by Shin-Ogata** [comment]
I checked to build our system using v6.1.6 and the result was OK! 💯 
Thank you for your quick release! 👍

**Comment by UrielCh** [comment]
do not forget my feedback :)
