### ISSUE TITLE
.sub(), add() etc behaves differently than substract/add (-/+) operations on Node and Python

### ISSUE THREAD

**Issue by LukaszSolo** [UrielCh/opencv4nodejs#34]
Hi,

I found maybe? a bug?

At least for `Mat`, substract Mat behaves differently under Python and Node (didn't test c++). 
Since Python is using numpys, substracting overflow results in it wrapped, while on Node it ends as zero.

This creates very subtle and hard to track issues if you try to port Python code to Node code.

Tbh I'm not sure if it's a bug, but if it's not, it might be worth mentioning in examples/docs

Python:
```python
import cv2
import numpy as np
m = np.zeros((1, 1), dtype = "uint8"), n = np.zeros((1, 1), dtype = "uint8")
m[0][0] = 2; n[0][0] = 4
print((m - n)[0][0])
```

results in `254`

Node:
```javascript
const cv = require('@u4/opencv4nodejs');
let m = new cv.Mat(1, 1, cv.CV_8U); let n = new cv.Mat(1, 1, cv.CV_8U);
m.set(0, 0, 2); n.set(0, 0, 4);
console.log(m.sub(n).at(0, 0));
```

results in `0`

To give a concrete example of when it quietly fails, Python examples for edge detection will include double gausianBlur with different strengths and the subtraction of those will be vastly different.
*OpenCV version* 4.5.5

*With OpenCV-contrib?* (extra modules): yes

*OS*: MacOSX

**Comment by UrielCh** [comment]
Hi,
I made some minor changes to your message; With some lint + color, it is more pleasant to read.

**Comment by LukaszSolo** [comment]
Hi, thank you for prompt reply. Unfortunately, turns out it's a feature:

https://docs.opencv.org/4.x/d0/d86/tutorial_py_image_arithmetics.html

```There is a difference between OpenCV addition and Numpy addition. OpenCV addition is a saturated operation while Numpy addition is a modulo operation.```

What that means though, is this example:

https://github.com/UrielCh/opencv4nodejs/blob/be727d680b13b4f143b5e14ff449dc5792709826/examples/src/getStructureSimilarity.ts#L27

Will behave differently than the Python original version.

I'll update title to reflect that and we can close. I couldn't find an easy way how to replicate `-` behaviour with OpenCV, as there's no builtin modulo operation, and trying to replicate it with division doesn't work because for modulo you need `floor` while `mat.div()` uses round :(

**Comment by UrielCh** [comment]
for references:
https://github.com/UrielCh/opencv4nodejs/blob/master/cc/core/coreUtils.h
