### ISSUE TITLE
Info config message showing when starting the application in another directory.

### ISSUE THREAD

**Issue by TheoPierne** [UrielCh/opencv4nodejs#35]
# Info Message

When I'm starting my application from another directory (`node src/server.js`), it's showing the following info message:

```txt
info config no opencv4nodejs section found in C:\Users\User\Desktop\spot-sdk\spot-server-js\package.json
```

But if I'm starting it in the src directory (`node server.js`) it's doesn't show any info message in the console.

*OpenCV version* : 4.5.5

*With OpenCV-contrib?* (extra modules): no
*OS*: Windows 10

**Comment by UrielCh** [comment]
yep if no package.json is found, no message is displayed.

Is it better to display one?

maybe.

**Comment by TheoPierne** [comment]
Thanks for your reply !

As I can read in the readme file, the `opencv4nodejs` section in the `package.json`'s file is deprecated, so I think it doesn't make sense to have an info message to notify when there is no `opencv4nodejs`'s section ?

I'm maybe wrong ?

**Comment by UrielCh** [comment]
I flag it as deprecated, but since this was mostly used, I will keep it functional.

My approach is building OpenCV using `build-opencv` command line.

**Comment by TheoPierne** [comment]
Oh, I see sorry for the inconvenience I am closing this issue. 

Have a good day !
