### ISSUE TITLE
It lacks the constants for the `CV_16F` depth.

### ISSUE THREAD

**Issue by issuefiler** [UrielCh/opencv4nodejs#52]
OpenCV supports the `CV_16F` depth.

https://github.com/opencv/opencv/blob/17234f82d025e3bbfbf611089637e5aa2038e7b8/modules/core/include/opencv2/core/hal/interface.h#L80

```C++
#define CV_8U   0
#define CV_8S   1
#define CV_16U  2
#define CV_16S  3
#define CV_32S  4
#define CV_32F  5
#define CV_64F  6
#define CV_16F  7
```

But `@u4/opencv4nodejs` does not have the constants for that.

-----

You could modify

https://github.com/UrielCh/opencv4nodejs/blob/66d7d42abb17ae5c5f8b5cfe6bf7cb5409baf24a/cc/core/matTypes.h#L10-L17
to
```Javascript
static void initMatTypes(v8::Local<v8::Object> module) {
	FF_MAT_TYPE(CV_8U);
	FF_MAT_TYPE(CV_8S);
	FF_MAT_TYPE(CV_16U);
	FF_MAT_TYPE(CV_16S);
	FF_MAT_TYPE(CV_32S);
	FF_MAT_TYPE(CV_32F);
	FF_MAT_TYPE(CV_64F);
	FF_MAT_TYPE(CV_16F);
```

and

https://github.com/UrielCh/opencv4nodejs/blob/66d7d42abb17ae5c5f8b5cfe6bf7cb5409baf24a/cc/core/matTypes.h#L49-L53
to
```Javascript
	FF_MAT_TYPE(CV_64FC1);
	FF_MAT_TYPE(CV_64FC2);
	FF_MAT_TYPE(CV_64FC3);
	FF_MAT_TYPE(CV_64FC4);

	FF_MAT_TYPE(CV_16FC1);
	FF_MAT_TYPE(CV_16FC2);
	FF_MAT_TYPE(CV_16FC3);
	FF_MAT_TYPE(CV_16FC4);
}
```

to add them.

**Comment by UrielCh** [comment]
Yep 16F is... missing.

**Comment by UrielCh** [comment]
fixed
