### ISSUE TITLE
Failing to use prebuilt OpenCV from local environment

### ISSUE THREAD

**Issue by progmars** [UrielCh/opencv4nodejs#56]
*OpenCV version* 4.6.0
*With OpenCV-contrib?* no
*OS*: Windows 10

I have the following variables set in the same console where I'm running my app:

Defined environment variables:
```
set OPENCV4NODEJS_DISABLE_AUTOBUILD=1
set OPENCV_INCLUDE_DIR=D:\myproject\platform_libs\win\opencv\include
set OPENCV_LIB_DIR=D:\myproject\platform_libs\win\opencv\bin
set OPENCV_BIN_DIR=D:\myproject\platform_libs\win\opencv\bin
set PATH=%WINDIR%;%WINDIR%\System32;%NODEPATH%;%OPENCV_BIN_DIR%
```

When I print all those variables with echo, they come back correct.
When I installed `npm i @u4/opencv4nodejs` there were no errors, so I assume it found the paths.

However, when I try
```
const cv = require("@u4/opencv4nodejs");
```

I got an error:

```
Error: require("D:\myproject\app\node_modules\@u4\opencv4nodejs\build\Release\opencv4nodejs");   
          Failed with: Cannot find module 'D:\myproject\app\node_modules\@u4\opencv4nodejs\build\Release\opencv4nodejs'
Require stack:
- D:\myproject\app\node_modules\@u4\opencv4nodejs\lib\cvloader.js
- D:\myproject\app\node_modules\@u4\opencv4nodejs\lib\opencv4nodejs.js
- D:\myproject\app\business\shapedetector.js
- D:\myproject\app\controllers\frame.js
- D:\myproject\app\app.js, openCV binding not available, reed: 
          build-opencv --help
          And build missing file with:
          npx build-opencv --version 4.5.4 rebuild

          PS: a 'npm link' may help

    at getOpenCV (D:\myproject\app\node_modules\@u4\opencv4nodejs\lib\cvloader.js:104:23)        
    at loadOpenCV (D:\myproject\app\node_modules\@u4\opencv4nodejs\lib\opencv4nodejs.js:9:43)    
    at Object.<anonymous> (D:\myproject\app\node_modules\@u4\opencv4nodejs\lib\opencv4nodejs.js:24:12)
```

I suspect I might have messed up the folder structure, but the instructions do not explicitly mention which opencv folders should go where for bin and lib.

So, I have extracted all lib, exe and h files from opencv-4.6.0-vc14_vc15.exe into the D:\myproject\platform_libs\win\opencv the following way:

D:\myproject\platform_libs\win\opencv\include has a single subfolder opencv2 with all the h files inside from opencv-4.6.0-vc14_vc15.exe\opencv\build\include

D:\myproject\platform_libs\win\opencv\bin has files:

opencv_annotation.exe
opencv_interactive-calibration.exe
opencv_model_diagnostics.exe
opencv_version.exe
opencv_version_win32.exe
opencv_videoio_ffmpeg460_64.dll
opencv_videoio_msmf460_64.dll
opencv_visualisation.exe
opencv_world460.dll
opencv_world460.lib

I have extracted them from opencv-4.6.0-vc14_vc15.exe\opencv\build\x64\vc15\bin and opencv-4.6.0-vc14_vc15.exe\opencv\build\x64\vc15\lib

The folder `D:\myproject\app\node_modules\@u4\opencv4nodejs` does not have build folder at all. It has only bin\win32-x64-57 folder and there it has file opencv4nodejs.node.

I don't understand how is this require() supposed to work. If I have specified OPENCV_BIN_DIR, why does it still attempt to look for build\Release folder that should not even exist because I am not building OpenCV?

I also set `OPENCV4NODES_DEBUG_REQUIRE=1` to see the full log from cvloader.js. Here's what it prints:

```
info require require path is D:\myproject\app\node_modules\@u4\opencv4nodejs\build\Release\opencv4nodejs
info require failed to require cv with exception: Error: Cannot find module 'D:\myproject\app\node_modules\@u4\opencv4nodejs\build\Release\opencv4nodejs'
info require Require stack:
info require - D:\myproject\app\node_modules\@u4\opencv4nodejs\lib\cvloader.js
info require - D:\myproject\app\node_modules\@u4\opencv4nodejs\lib\opencv4nodejs.js
info require - D:\myproject\app\business\shapedetector.js
info require - D:\myproject\app\controllers\frame.js
info require - D:\myproject\app\app.js
info require attempting to add opencv binaries to path
info tryGetOpencvBinDir OPENCV_BIN_DIR environment variable is set
info require adding opencv binary dir to path: D:\myproject\platform_libs\win\opencv\bin
info require process.env.path: C:\WINDOWS;C:\WINDOWS\System32;D:\myproject\nodejs;D:\myproject\platform_libs\win\opencv\bin
Error: require("D:\myproject\app\node_modules\@u4\opencv4nodejs\build\Release\opencv4nodejs");   
          Failed with: Cannot find module 'D:\myproject\app\node_modules\@u4\opencv4nodejs\build\Release\opencv4nodejs'
Require stack:
- D:\myproject\app\node_modules\@u4\opencv4nodejs\lib\cvloader.js
- D:\myproject\app\node_modules\@u4\opencv4nodejs\lib\opencv4nodejs.js
- D:\myproject\app\app.js, openCV binding not available, reed: 
          build-opencv --help
          And build missing file with:
          npx build-opencv --version 4.5.4 rebuild

          PS: a 'npm link' may help

    at getOpenCV (D:\myproject\app\node_modules\@u4\opencv4nodejs\lib\cvloader.js:104:23)        
    at loadOpenCV (D:\myproject\app\node_modules\@u4\opencv4nodejs\lib\opencv4nodejs.js:9:43)    
    at Object.<anonymous> (D:\myproject\app\node_modules\@u4\opencv4nodejs\lib\opencv4nodejs.js:24:12)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (D:\myproject\app\business\shapedetector.js:4:12)
```

So, judging by the line `OPENCV_BIN_DIR environment variable is set` it has picked up the variable and the path. Still, it attempts require() `Release` path anyway - but of course it will fail because OpenCV is in OPENCV_BIN_DIR (or in bin\win32-x64-57) and not in build\Release\opencv4nodejs. So why does it attempt to require the nonexistent path at all?

I tried
```
npm link
build-opencv --nobuild rebuild
```

It said:
```
added 1 package, and audited 3 packages in 598ms
'build-opencv' is not recognized as an internal or external command,
operable program or batch file.
```

What am I doing wrong? Is there a cleaner way to get a prebuilt package of OpenCV + contrib that would work on Win10 through opencv4nodejs?

**Comment by UrielCh** [comment]
1- Please list `D:\myproject\app\node_modules\@u4\opencv4nodejs\build\Release\`content.
2- try the OpenCV chocolate build; this build should be autodetected.
3- npm link solve global OpenCV setup, not your case.

**Comment by progmars** [comment]
There was no folder `build` in `D:\myproject\app\node_modules\@u4\opencv4nodejs` at all. But there was `D:\myproject\app\node_modules\@u4\opencv4nodejs\bin\win32-x64-57` folder and it had file `opencv4nodejs.node`.

Meanwhile, I have switched to opencv.js which is distributed by OpenCV themselves; it seems easier to set up, although it required fiddling with emscripten and fake DOM and canvas for nodejs.

It's so confusing, there are multiple OpenCV bindings on npm and none of them is as simple to install as on Python. Sigh.

**Comment by UrielCh** [comment]
I need to write some benchmarks to compare the two nodeJS versions.
For small processing, keep the WASM build.
Now that I have a 3060 I should retry some heavy benchmarks.
