### ISSUE TITLE
 'dump': is not a member of cv: 'cv::dnn::dnn4_v20190122::Net' 

### ISSUE THREAD

**Issue by BartaG512** [UrielCh/opencv4nodejs#58]
I get this during install on Windows 

 \opencv4nodejs\cc\dnn\Net.cc(115,48): error C2039: 'dump': is not a member of 'cv::dnn::dnn4_v20190122::Net' [ \opencv4nodejs\build\opencv4nodejs.vcxproj]
c:\tools\opencv\build\include\opencv2\dnn\dnn.hpp(366): message : see declaration of 'cv::dnn::dnn4_v20190122::Net' [ \opencv4nodejs\build\opencv4nodejs.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit ( opencv4nodejs\node_modules\node-gyp\lib\build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "opencv4nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--jobs" "max" "--release"
gyp ERR! cwd  \opencv4nodejs
gyp ERR! node -v v16.15.0
gyp ERR! node-gyp -v v9.3.0
gyp ERR! not ok

gyp info spawn args ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (opencv4nodejs\node_modules\node-gyp\lib\build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "opencv4nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--jobs" "max" "--release"
gyp ERR! cwd opencv4nodejs
gyp ERR! node -v v16.15.0
gyp ERR! node-gyp -v v9.3.0
gyp ERR! not ok

# Manual Build - Environment Information
 
*OpenCV version* (example 3.4.1):  4.1.0

*With OpenCV-contrib?* (extra modules): no 
OS: Windows 10
Nodejs: v14.17.0

**Comment by UrielCh** [comment]
First upgrade your openCV I think that I drop v 4.1.0 support.
this version is too old.

**Comment by UrielCh** [comment]
Readme updated
