### ISSUE TITLE
Installation fails for macOS and yarn

### ISSUE THREAD

**Issue by gruffT** [UrielCh/opencv4nodejs#6]
Any help much appreciated.

# Error Message

Installation runs without error, both the node module and the build
```
export OPENCV_BUILD_ROOT=~/opencv
yarn add opencv4nodejs
yarn run opencv-build-npm
```

package.json config:
```
  "opencv4nodejs": {
    "autoBuildOpencvVersion": "4.5.4"
  }
```

Attempting to use in a trivial script:
```
const cv = require('@u4/opencv4nodejs');
console.log(cv.getBuildInformation());
```
results in:
```
Error: Cannot find module '/Users/<...>/node_modules/@u4/opencv4nodejs/build/Release/opencv4nodejs'
```
Setting ```OPENCV4NODES_DEBUG_REQUIRE=1;``` shows:
```
info require require path is /Users/<...>/node_modules/@u4/opencv4nodejs/build/Release/opencv4nodejs
info require failed to require cv with exception: Error: Cannot find module '/Users/<...>/node_modules/@u4/opencv4nodejs/build/Release/opencv4nodejs'
```
Checking node_modules/u4/opencv4nodejs shows there is no build directory.

*OpenCV version* (example 3.4.1): 4.5.4

*With OpenCV-contrib?* (extra modules): yes/no? I don't think so.

*OS*: Windows 7 / 8 / 10? / MacOSX? / Ubuntu? ... Mac osX BigSur 11.6.2

*Node* tried with v16 and v14

**Comment by UrielCh** [comment]
First of all stop using 
opencv4nodejs in package.json, I keep it retro-compatibility but for a clean project, you should drop it.

by using this code, you should be able to read an important notice in your error log, saying that you should exec:

```bash
build-opencv --verion=4.5.4 build
```
add this step in a script in your package.json.

please double-check your full message error. you should see this message, if not, please send more error logs.

I may have forgot to display it in some cases.

**Comment by UrielCh** [comment]
fill free to open a pull request with some doc improvement.

**Comment by UrielCh** [comment]
doc updated in v 6.0.10

**Comment by gruffT** [comment]
Thank you, clearing down node_modules and running that worked.  Thank you for improving the docs and for everything you do on such a great tool.
