### ISSUE TITLE
Bug in OpenCVBuildEnv.js "call to undefined function toLowerCase()"

### ISSUE THREAD

**Issue by Sebastian-Habiger** [UrielCh/opencv4nodejs#62]
Hello,

since version 6.3.0 there is a bug inside toBool function of OpenCVBuildEnv.js

Using "disableAutoBuild": 1 as described by documentation does not work anymore due to the fact that toLowerCase does not exist on type number.

OpenCVBuildEnv.js
```
function toBool(value) {
  if (!value)
      return false;
  if (typeof value === 'boolean')
      return value;
  value = value.toLowerCase();
  // ...
}
```

Workaround:
Use a string value instead.
"disableAutoBuild": "1"

I have created a pull-request addressing that issue.

**Comment by UrielCh** [comment]
For me value should be string only, but if you get boolean here, you can open a PR.
and use "1" for the moment.
