### ISSUE TITLE
STATUS_STACK_BUFFER_OVERRUN when implementing minAreaRect as global function

### ISSUE THREAD

**Issue by Sebastian-Habiger** [UrielCh/opencv4nodejs#66]
Hi,

I am trying to implement the minAreaRect function outside the Contour class. Compilation works, and even when I remove the call to cv::minAreaRect this function returns without an error. But when calling cv::minAreaRect this function breaks and I get

"Process finished with exit code -1073740791 (0xC0000409) STATUS_STACK_BUFFER_OVERRUN"

```CC
NAN_METHOD(Imgproc::MinAreaRect) {
  FF::TryCatch tryCatch("Imgproc::MinAreaRect");
  if (!info[0]->IsArray()) {
	  return tryCatch.throwError("expected arg 0 to be an array");
  }
  std::vector<cv::Point2d> pts2d;
  if (Point2::ArrayWithCastConverter<cv::Point2d>::arg(0, &pts2d, info)) {
    return tryCatch.reThrow();
  }
  info.GetReturnValue().Set(RotatedRect::Converter::wrap(cv::minAreaRect(pts2d)));
}
```

I am working on a Windows 11 Computer.

I am guessing I am doing the conversion wrong, but I have no idea, what is wrong with that code.
Would someone be able to guide me in the right direction, please?

**Comment by UrielCh** [comment]
hi, try to sync your code, I made lots of changes today.

then push your change to your fork, so I will be able to check that.

**Comment by Sebastian-Habiger** [comment]
Thanks in advance. I did merge your changes.
Besides I have another question: I would like to add the magnitude and phase function from the opencv core. What is the recommended way of doing this? Should I use the CatchCvExceptionWorker or CvBinding instead of a direct implementation?
Especially in regard to contribution.

**Comment by UrielCh** [comment]
I'm in some cuda stuff for now, my CPU is ... under pressure, and I can not test your code.

by the way, I publish a new version today, and your fork is out of sync 😄
