### ISSUE TITLE
Ubuntu/Raspberry Pi OS - Can't open camera by index

### ISSUE THREAD

**Issue by jakewarrenblack** [UrielCh/opencv4nodejs#89]
Hello, I've managed to install this package without issue on the Raspberry Pi 4B after reading the instructions on this issue:

https://github.com/UrielCh/opencv4nodejs/issues/67

The example code provided runs fine:
![image](https://user-images.githubusercontent.com/47800618/225674061-cb5f785e-8079-4fd0-8114-a0fafeaf0362.png)

But when trying to run my own code, opencv can't open the webcam (device 0)

This runs fine on Windows. For the Raspberry Pi, I've read that only the legacy camera driver supports opencv, so I  switched to the legacy driver, but that didn't help. I've read through several similar issues on this repository, the opencv forums, and the original opencv4nodejs repository, but nothing has helped. I understand it's possible this problem has nothing to do with opencv4nodejs itself, and may relate purely to opencv, but any help you can offer is much appreciated.

I've tried running this on both the Raspberry Pi and my laptop running Ubuntu, neither worked.

The error I'm getting looks like this:
![image](https://user-images.githubusercontent.com/47800618/225492589-313ee8d1-152d-4143-8280-ba9631129996.png)

It is just a warning rather than an error, but no webcam feed is captured.

Using Python, I have no problem capturing the webcam feed from the same device.

Result of running [this](https://gist.githubusercontent.com/3dsf/5f80752231f10e1283741be8520bb503/raw/3658032b58568a1607f96cb73a4ec302706061d8/listCams.py) script to find valid opencv/ffmpeg devices

![image](https://user-images.githubusercontent.com/47800618/225663182-a9aec2bb-0b1a-4b82-98f7-82eadf4ef720.png)

Device list:

![image](https://user-images.githubusercontent.com/47800618/225663379-0144c6b6-bcf4-4403-b73b-b1c0031928f3.png)

I've tried using both those device indexes (0, 1), and -1. I've tried setting the capture method as cv.V4L and cv.V4L2.

I've tried passing a gstreamer pipeline straight into VideoCapture, as suggested [here](https://forums.developer.nvidia.com/t/v4l2src-using-opencv-gstreamer-is-not-working-in-jetson-xavier-nx/156323)

I read [here](https://forum.opencv.org/t/opencv-videocapture-is-not-functioning-when-deployed-in-ubuntu-server/3560/2) that I should use the path to the video source e.g. '/dev/video0' instead of just an index, like on Windows, which also didn't work.

The script should have permission to access both /dev/video0' and /dev/video1', so it's not a permissions issue.

I already had ffmpeg installed when installing opencv4nodejs, so I'm not sure if it could be related to [this](https://github.com/justadudewhohacks/opencv4nodejs/issues/315) issue.

I've also tried the solution mentioned at the bottom [here](https://github.com/peterbraden/node-opencv/issues/631)

Could you recommend anything I can do? I'm wondering if maybe I need to use my own opencv build, with gstreamer enabled.

**Comment by jakewarrenblack** [comment]
I should add that v4l2-ctl is recording video in motion jpeg format on the Raspberry Pi without issue, using the same device at index 0 (/dev/video0). Confused as to why opencv is failing to create a new `VideoCapture `instance with `0` and `cv.CAP_V4L2` as arguments, which seems like the same thing.

**Comment by jakewarrenblack** [comment]
Solved. On Windows, this ran just fine:

```
  while(true) {
    const capture = new cv.VideoCapture(0)
    
    let frame = capture.read();

    if (frame.empty) {
      cap.reset();
      frame = cap.read();
    }

    // Call the onFrame callback and wait for it to complete
    const result = await onFrame(frame);

    if (result) {
      return result;
    }

    // Delay before reading the next frame
    await new Promise(resolve => setTimeout(resolve, delay));

  }
```

On Linux, I just needed to move the `const capture = new VideoCapture(0)` line _outside_ the while loop. I realise creating a new VideoCapture instance every time the loop ran probably didn't make sense anyway, but it worked fine on windows ¯\_(ツ)_/¯

Thanks anyway

**Comment by UrielCh** [comment]
nice self fix 👍
