### ISSUE TITLE
Latest version 6.5.2 is not published on npm yet

### ISSUE THREAD

**Issue by Shin-Ogata** [UrielCh/opencv4nodejs#99]
Thank you for your great job.
It seems that the latest v6.5.2 module is not published on npm yet.
Could you publish the latest version to npm?

We need a version with the following issues fixed.

- https://github.com/UrielCh/opencv4nodejs/issues/70
- https://github.com/UrielCh/npm-opencv-build/commit/088a83c2368adea4a1fc6de7feaec18f47a174ef

Thanks a lot.

**Comment by UrielCh** [comment]
https://github.com/UrielCh/opencv4nodejs/actions/runs/5052969333/jobs/9066346143


ARff...

**Comment by UrielCh** [comment]
I re-run the task

**Comment by UrielCh** [comment]
it failed again with:
> sudo apt-get install -y libopencv-dev libopencv-features2d-dev

**Comment by UrielCh** [comment]
build pass.
